Cypress.Commands.add('createProposal', () => {
    
    cy.visit('/patient/73749/proposal/create')
    cy.url().should('include', '/patient/73749/proposal/create')
    cy.get('#parceiroId').click()
    cy.contains('Cartão de Todos').click()
    cy.get('#areaExpertise').click()
    cy.contains('span', 'Acupuntura')
    cy.contains('Acupuntura').click()        
    cy.get('#profissional').click()
    cy.contains('Dr. Pedro Teste').click()
    cy.get('#statusProposal').click()
    cy.contains('Aprovada pelo cliente').click()
    cy.get('mat-select[formcontrolname="tipoProcedimento"]')
    cy.contains('span', 'Nome Procedimento').should('be.visible')    
    cy.get('input[formcontrolname="procedimento"]').click()
    cy.contains('span', ' 2005 I Procedimento ').click()
    cy.contains('button', 'Adicionar').click()
    cy.contains('span', 'Selecione um executante').click()
    cy.contains('span', 'Teste Fran Tavares').click()
    cy.contains('span', 'Receber').click()
    cy.contains('button', 'Salvar').click()          
    cy.wait(5000)     
    cy.contains('button', 'Editar').first().click()
    cy.contains('span', 'Receber').should('be.visible').click()
})

Cypress.Commands.add('createProposalI', () => {
    cy.get('#patient').click()
    cy.get('.d-flex > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').type('111701035618')
    cy.contains('p', 'Pesquisar').click()    
    cy.wait(1600)
    cy.contains('button', 'edit').click()
    cy.contains('span', 'Propostas').click()
    cy.contains('button', 'Nova Proposta').click()
    cy.url().should('include', '/patient/73749/proposal/create')    
    cy.get('#parceiroId').click()
    cy.contains('Cartão de Todos').click()
    cy.get('#areaExpertise').click()
    cy.contains('span', 'Acupuntura')
    cy.contains('Acupuntura').click()        
    cy.get('#profissional').click()
    cy.contains('Dr. Pedro Teste').click()
    cy.get('#statusProposal').click()
    cy.contains('Aprovada pelo cliente').click()
    cy.get('mat-select[formcontrolname="tipoProcedimento"]')
    cy.contains('span', 'Nome Procedimento').should('be.visible')    
    cy.get('input[formcontrolname="procedimento"]').click()
    cy.contains('span', ' 2005 I Procedimento ').click()
    cy.contains('button', 'Adicionar').click()
    cy.contains('span', 'Selecione um executante').click()
    cy.contains('span', 'Teste Fran Tavares').click()
    cy.contains('span', 'Receber').click()
    cy.contains('button', 'Salvar').click()    
    //cy.get('.d-flex > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex > .mat-form-field-infix').type('111701035618')
   // cy.contains('p', 'Pesquisar').click()    
    cy.wait(1600)
    cy.contains('button', 'Editar').click()
    cy.contains('span', 'Propostas').click()   
    cy.contains('button', 'Editar').first().click()
    cy.contains('span', 'Receber').should('be.visible').click()
})